name: cdk-github-actions
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Use Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Use configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: 'arn:aws:iam::654654329506:role/CdkDeployRole' # Gitデプロイ用のAWS IAM ロールの ARN

      - name: Setup dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: CDK Diff Check
        # if: contains(github.event_name, 'pull_request')
        run: npm run cdk:diff

      - name: CDK Deploy
        # if: contains(github.event_name, 'push') 
        run: npm run cdk:deploy

